import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-smarthome',
  templateUrl: './smarthome.component.html',
  styleUrls: ['./smarthome.component.css']
})
export class SmarthomeComponent implements OnInit {
  category=[

    {
      id:1,
      text:'Nhà Thông Minh',
      routerLink:'/smarthome'
    },
      ]
      product = [
        {
          id: 1,
          url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/k/s/ksp_v2.jpg',
          name: 'Máy lọc không khí Xiaomi Air Purifier 4 Lite',
          old: '3.590.000 ₫',
          current: '3.990.000 ₫',
          sold: '99 đã bán',
          brand: 'SmartStore',
          origin_name: 'VN/A',
          check: 'Yêu thích',
          percent: '10%',
          label: 'GIẢM',
        },
        {
          id: 1,
          url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/k/s/ksp_v2.jpg',
          name: 'Máy lọc không khí Xiaomi Air Purifier 4 Lite',
          old: '3.590.000 ₫',
          current: '3.990.000 ₫',
          sold: '99 đã bán',
          brand: 'SmartStore',
          origin_name: 'VN/A',
          check: 'Yêu thích',
          percent: '10%',
          label: 'GIẢM',
        },
        {
          id: 1,
          url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/k/s/ksp_v2.jpg',
          name: 'Máy lọc không khí Xiaomi Air Purifier 4 Lite',
          old: '3.590.000 ₫',
          current: '3.990.000 ₫',
          sold: '99 đã bán',
          brand: 'SmartStore',
          origin_name: 'VN/A',
          check: 'Yêu thích',
          percent: '10%',
          label: 'GIẢM',
        },
        {
          id: 1,
          url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/k/s/ksp_v2.jpg',
          name: 'Máy lọc không khí Xiaomi Air Purifier 4 Lite',
          old: '3.590.000 ₫',
          current: '3.990.000 ₫',
          sold: '99 đã bán',
          brand: 'SmartStore',
          origin_name: 'VN/A',
          check: 'Yêu thích',
          percent: '10%',
          label: 'GIẢM',
        },
        {
          id: 1,
          url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/k/s/ksp_v2.jpg',
          name: 'Máy lọc không khí Xiaomi Air Purifier 4 Lite',
          old: '3.590.000 ₫',
          current: '3.990.000 ₫',
          sold: '99 đã bán',
          brand: 'SmartStore',
          origin_name: 'VN/A',
          check: 'Yêu thích',
          percent: '10%',
          label: 'GIẢM',
        },
        {
          id: 1,
          url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/k/s/ksp_v2.jpg',
          name: 'Máy lọc không khí Xiaomi Air Purifier 4 Lite',
          old: '3.590.000 ₫',
          current: '3.990.000 ₫',
          sold: '99 đã bán',
          brand: 'SmartStore',
          origin_name: 'VN/A',
          check: 'Yêu thích',
          percent: '10%',
          label: 'GIẢM',
        },
        {
          id: 1,
          url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/k/s/ksp_v2.jpg',
          name: 'Máy lọc không khí Xiaomi Air Purifier 4 Lite',
          old: '3.590.000 ₫',
          current: '3.990.000 ₫',
          sold: '99 đã bán',
          brand: 'SmartStore',
          origin_name: 'VN/A',
          check: 'Yêu thích',
          percent: '10%',
          label: 'GIẢM',
        },
        {
          id: 1,
          url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/k/s/ksp_v2.jpg',
          name: 'Máy lọc không khí Xiaomi Air Purifier 4 Lite',
          old: '3.590.000 ₫',
          current: '3.990.000 ₫',
          sold: '99 đã bán',
          brand: 'SmartStore',
          origin_name: 'VN/A',
          check: 'Yêu thích',
          percent: '10%',
          label: 'GIẢM',
        },
        {
          id: 1,
          url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/k/s/ksp_v2.jpg',
          name: 'Máy lọc không khí Xiaomi Air Purifier 4 Lite',
          old: '3.590.000 ₫',
          current: '3.990.000 ₫',
          sold: '99 đã bán',
          brand: 'SmartStore',
          origin_name: 'VN/A',
          check: 'Yêu thích',
          percent: '10%',
          label: 'GIẢM',
        },
        {
          id: 1,
          url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/k/s/ksp_v2.jpg',
          name: 'Máy lọc không khí Xiaomi Air Purifier 4 Lite',
          old: '3.590.000 ₫',
          current: '3.990.000 ₫',
          sold: '99 đã bán',
          brand: 'SmartStore',
          origin_name: 'VN/A',
          check: 'Yêu thích',
          percent: '10%',
          label: 'GIẢM',
        },
        {
          id: 1,
          url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/k/s/ksp_v2.jpg',
          name: 'Máy lọc không khí Xiaomi Air Purifier 4 Lite',
          old: '3.590.000 ₫',
          current: '3.990.000 ₫',
          sold: '99 đã bán',
          brand: 'SmartStore',
          origin_name: 'VN/A',
          check: 'Yêu thích',
          percent: '10%',
          label: 'GIẢM',
        },
        {
          id: 1,
          url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/k/s/ksp_v2.jpg',
          name: 'Máy lọc không khí Xiaomi Air Purifier 4 Lite',
          old: '3.590.000 ₫',
          current: '3.990.000 ₫',
          sold: '99 đã bán',
          brand: 'SmartStore',
          origin_name: 'VN/A',
          check: 'Yêu thích',
          percent: '10%',
          label: 'GIẢM',
        },
        {
          id: 1,
          url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/k/s/ksp_v2.jpg',
          name: 'Máy lọc không khí Xiaomi Air Purifier 4 Lite',
          old: '3.590.000 ₫',
          current: '3.990.000 ₫',
          sold: '99 đã bán',
          brand: 'SmartStore',
          origin_name: 'VN/A',
          check: 'Yêu thích',
          percent: '10%',
          label: 'GIẢM',
        },
        {
          id: 1,
          url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/k/s/ksp_v2.jpg',
          name: 'Máy lọc không khí Xiaomi Air Purifier 4 Lite',
          old: '3.590.000 ₫',
          current: '3.990.000 ₫',
          sold: '99 đã bán',
          brand: 'SmartStore',
          origin_name: 'VN/A',
          check: 'Yêu thích',
          percent: '10%',
          label: 'GIẢM',
        },
        {
          id: 1,
          url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/k/s/ksp_v2.jpg',
          name: 'Máy lọc không khí Xiaomi Air Purifier 4 Lite',
          old: '3.590.000 ₫',
          current: '3.990.000 ₫',
          sold: '99 đã bán',
          brand: 'SmartStore',
          origin_name: 'VN/A',
          check: 'Yêu thích',
          percent: '10%',
          label: 'GIẢM',
        },
        {
          id: 1,
          url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/k/s/ksp_v2.jpg',
          name: 'Máy lọc không khí Xiaomi Air Purifier 4 Lite',
          old: '3.590.000 ₫',
          current: '3.990.000 ₫',
          sold: '99 đã bán',
          brand: 'SmartStore',
          origin_name: 'VN/A',
          check: 'Yêu thích',
          percent: '10%',
          label: 'GIẢM',
        },
        {
          id: 1,
          url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/k/s/ksp_v2.jpg',
          name: 'Máy lọc không khí Xiaomi Air Purifier 4 Lite',
          old: '3.590.000 ₫',
          current: '3.990.000 ₫',
          sold: '99 đã bán',
          brand: 'SmartStore',
          origin_name: 'VN/A',
          check: 'Yêu thích',
          percent: '10%',
          label: 'GIẢM',
        },
        {
          id: 1,
          url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/k/s/ksp_v2.jpg',
          name: 'Máy lọc không khí Xiaomi Air Purifier 4 Lite',
          old: '3.590.000 ₫',
          current: '3.990.000 ₫',
          sold: '99 đã bán',
          brand: 'SmartStore',
          origin_name: 'VN/A',
          check: 'Yêu thích',
          percent: '10%',
          label: 'GIẢM',
        },
      ]

  constructor() { }

  ngOnInit(): void {
  }

}
