import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-container',
  templateUrl:'./container.component.html',
  styleUrls: ['./container.component.css']
})
export class ContainerComponent implements OnInit {
  category=[

{
  id:1,
  text:'Điện Thoại',
  routerLink: '/telephone'
},
{
  id:1,
  text:'Laptop,PC,Màn Hình',
  routerLink: '/laptop'
},
{
  id:1,
  text:'Tablet',
  routerLink: '/tablet'
},
{
  id:1,
  text:'Âm Thanh',
  routerLink:'/sound'
},
{
  id:1,
  text:'Đồng Hồ',
  routerLink:'/clock'
},
{
  id:1,
  text:'Thu Cũ',
  routerLink:'/oldautumn'
},
{
  id:1,
  text:'Hàng Cũ',
  routerLink:'/secondhandgoods'
},
{
  id:1,
  text:'Tivi',
  routerLink:'/television'
},
{
  id:1,
  text:'Tin Công Nghệ',
  routerLink:'/technews'
},
{
  id:1,
  text:'Khuyễn Mãi',
  routerLink:'/promotions'
},
{
  id:1,
  text:'Phụ Kiện',
  routerLink:'/accessory'
},
{
  id:1,
  text:'Nhà Thông Minh',
  routerLink:'/smarthome'
},
  ]
  product = [
    {
      id: 1,
      url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/i/p/iphone_13-_pro-5_4.jpg',
      name: 'iPhone 13 Pro Max 128GB | Chính hãng VN/A',
      old: '34.990.000 ₫',
      current: '29.350.000 ₫',
      sold: '99 đã bán',
      brand: 'SmartStore',
      origin_name: 'VN/A',
      check: 'Yêu thích',
      percent: '10%',
      label: 'GIẢM',
    },
    {
      id: 2,
      url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/m/a/macbook-pro-2021-007_1.jpg',
      name: 'Macbook Pro 14 inch 2021 | Chính hãng Apple Việt Nam',
      old: '35.990.000 ₫',
      current: '30.800.000 ₫',
      sold: '99 đã bán',
      brand: 'SmartStore',
      origin_name: 'VN/A',
      check: 'Yêu thích',
      percent: '10%',
      label: 'GIẢM',
    },
    {
      id: 3,
      url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/i/m/imac_21_inch_2020_mac24h_xuo7-a6_1.png',
      name: 'Apple iMac 27 5K 2020 i5 3.1 8GB 256GB Radeon 5300 Chính Hãng (MXWT2)',
      old: '52.990.000 ₫',
      current: '49.990.000 đ',
      sold: '99 đã bán',
      brand: 'SmartStore',
      origin_name: 'VN/A',
      check: 'Yêu thích',
      percent: '10%',
      label: 'GIẢM',
    },
    {
      id: 4,
      url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/m/a/mac-studio-1646775245-8194-1646775416-removebg-preview.jpg',
      name: 'Mac Studio 2022 M1 Max 10 CPU | Chính hãng Apple Việt Nam',
      current: '59.990.000 ₫',
      sold: 'SẮP VỀ HÀNG',
      brand: 'APPLE',
      origin_name: 'VN/A',
      check: 'Yêu thích',
      percent: '10%',
      label: 'GIẢM',
    },
    {
      id: 5,
      url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/a/p/apple_studio_display_2022_co_chan_de_1.jpg',
      name: 'Apple Studio Display 27 5K Chân đế cố định 2022 chính hãng',
      current: '43.990.000 ₫',
      sold: 'SẮP VỀ HÀNG',
      brand: 'SmartStore',
      origin_name: 'VN/A',
      check: 'Yêu thích',
      percent: '10%',
      label: 'GIẢM',
    },
    {
      id: 6,
      url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/a/p/apple_studio_display_2022_nano_2.jpg',
      name: 'Apple Studio Display 27 5K Màn Nano Chân đế điều chỉnh 2022 chính hãng',
      current: '62.990.000 ₫',
      sold: 'SẮP VỀ HÀNG',
      brand: 'SmartStore',
      origin_name: 'VN/A',
      check: 'Yêu thích',
      percent: '10%',
      label: 'GIẢM',
    },
    {
      id: 7,
      url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/a/p/apple_studio_display_2022_kong_chan_de_2.jpg',
      name: 'Apple Studio Display 27 5K Màn Nano không chân đế 2022 chính hãng',
      current: '51.990.000 ₫',
      sold: 'SẮP VỀ HÀNG',
      brand: 'SmartStore',
      origin_name: 'VN/A',
      check: 'Yêu thích',
      percent: '10%',
      label: 'GIẢM',
    },
    {
      id: 8,
      url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/i/p/ipad-pro-12-9-2021-1-0009_2.jpg',
      name: 'Apple iPad Pro 12.9 2021 M1 5G 128GB I Chính hãng Apple Việt Nam',
      old: '33.990.000 ₫',
      current: '29.500.000 ₫',
      sold: '99 đã bán',
      brand: 'SmartStore',
      origin_name: 'VN/A',
      check: 'Yêu thích',
      percent: '10%',
      label: 'GIẢM',
    },
    {
      id: 9,
      url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/i/p/ipad_pro_11_2020_wifi_128gb.png',
      name: 'iPad Pro 11 2020 WiFi 128GB I Chính hãng Apple Việt Nam',
      old: '21.990.000 ₫',
      current: '21.000.000 ₫',
      sold: '99 đã bán',
      brand: 'SmartStore',
      origin_name: 'VN/A',
      check: 'Yêu thích',
      percent: '10%',
      label: 'GIẢM',
    },
    {
      id:10,
      url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/i/p/iphone_13_pro_max_alpine_green_pure_back_iphone_13_pro_max_alpine_green_pure_front_2-up_screen__usen.png',
      name: 'iPhone 13 Pro Max 128GB - Xanh lá | Chính hãng VN/A',
      old: '34.990.000 ₫',
      current: '31.490.000 ₫',
      sold: 'HÀNG ĐẶT TRƯỚC',
      brand: 'SmartStore',
      origin_name: 'VN/A',
      check: 'Yêu thích',
      percent: '10%',
      label: 'GIẢM',
    },
    {
      id: 11,
      url: 'https://image.cellphones.com.vn/220x/media/catalog/product/1/8/18_2_29.jpg',
      name: 'Laptop Asus Vivobook 13 Slate Oled T3300KA',
      current: '17.790.000 ₫',
      sold: '99 đã bán',
      brand: 'SmartStore',
      origin_name: 'VN/A',
      check: 'Yêu thích',
      percent: '10%',
      label: 'GIẢM',
    },
    {
      id: 12,
      url: 'https://image.cellphones.com.vn/220x/media/catalog/product/2/_/2_64_22.jpg',
      name: 'Laptop Gaming Acer Nitro 5 AN515 45 R6EV',
      old: '23.990.000 ₫',
      current: '20.190.000 ₫',
      sold: '99 đã bán',
      brand: 'SmartStore',
      origin_name: 'VN/A',
      check: 'Yêu thích',
      percent: '10%',
      label: 'GIẢM',
    },
    {
      id: 13,
      url: 'https://image.cellphones.com.vn/220x/media/catalog/product/a/i/airpod-3.jpg',
      name: 'Tai nghe Bluetooth Apple AirPods 3 | Chính hãng Apple Việt Nam',
      old: '4.990.000 đ',
      current: '4.490.000 ',
      sold: '99 đã bán',
      brand: 'SmartStore',
      origin_name: 'VN/A',
      check: 'Yêu thích',
      percent: '10%',
      label: 'GIẢM',
    },
    {
      id: 14,
      url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/220x175/9df78eab33525d08d6e5fb8d27136e95/a/i/airpods-2_6.jpg',
      name: 'Tai nghe Bluetooth Apple AirPods 2 VN/A',
      old: '3.999.000đ',
      current: '2.850.000đ',
      sold: '99 đã bán',
      brand: 'SmartStore',
      origin_name: 'VN/A',
      check: 'Yêu thích',
      percent: '10%',
      label: 'GIẢM',
    },
    {
      id: 15,
      url: 'https://image.cellphones.com.vn/220x/media/catalog/product/b/u/buds-live_1.jpg',
      name: 'Tai nghe Bluetooth Samsung Galaxy Buds Live',
      old: '4.490.000 ₫',
      current: '1.490.000 ₫',
      sold: '99 đã bán',
      brand: 'SmartStore',
      origin_name: 'VN/A',
      check: 'Yêu thích',
      percent: '10%',
      label: 'GIẢM',
    },
    {
      id:16,
      url: 'https://image.cellphones.com.vn/220x/media/catalog/product/w/a/watch_3_leather.jpg',
      name: 'Đồng hồ thông minh Huawei Watch GT3 dây da',
      old: '6.990.000 ₫',
      current: '5.490.000 ₫',
      sold: '99 đã bán',
      brand: 'SmartStore',
      origin_name: 'VN/A',
      check: 'Yêu thích',
      percent: '10%',
      label: 'GIẢM',
    },
    {
      id: 17,
      url: 'https://image.cellphones.com.vn/220x/media/catalog/product/a/c/active-s1-blue-thumb.jpg',
      name: 'Đồng hồ thông minh Xiaomi Watch S1 Active',
      old: '5.999.000đ',
      current: '4.490.000 đ',
      sold: '99 đã bán',
      brand: 'SmartStore',
      origin_name: 'VN/A',
      check: 'Yêu thích',
      percent: '10%',
      label: 'GIẢM',
    },
    {
      id: 18,
      url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/s/e/series_7-45-thumb_1.jpg',
      name: 'Apple Watch Series 7 45mm (GPS) Viền nhôm dây cao su | Chính hãng VN/A',
      old: '12.999.000đ',
      current: '10.590.000 ₫',
      sold: '99 đã bán',
      brand: 'SmartStore',
      origin_name: 'VN/A',
      check: 'Yêu thích',
      percent: '10%',
      label: 'GIẢM',
    },
    {
      id: 19,
      url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/s/e/series_7-thumb_2.jpg',
      name: 'Apple Watch Series 7 41mm (GPS) Viền nhôm dây cao su | Chính hãng VN/A',
      old: '11.990.000 ₫',
      current: '9.390.000 đ',
      sold: '99 đã bán',
      brand: 'SmartStore',
      origin_name: 'VN/A',
      check: 'Yêu thích',
      percent: '10%',
      label: 'GIẢM',
    },
    {
      id: 20,
      url: 'https://image.cellphones.com.vn/220x/media/catalog/product/t/e/template_dongho123-recovered_5.jpg',
      name: 'Vòng đeo tay thông minh Xiaomi Mi Band 6',
      old: '1.999.000đ',
      current: '850.000đ',
      sold: '99 đã bán',
      brand: 'SmartStore',
      origin_name: 'VN/A',
      check: 'Yêu thích',
      percent: '10%',
      label: 'GIẢM',
    },
  ];

  constructor() { }

  ngOnInit(): void {
  }

}
