import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-clock',
  templateUrl: './clock.component.html',
  styleUrls: ['./clock.component.css']
})
export class ClockComponent implements OnInit {
  category=[

    {
      id:1,
      text:'Đồng Hồ',
      routerLink:'/clock'
    },
   
      ]
      product = [
        {
          id: 18,
          url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/s/e/series_7-45-thumb_1.jpg',
          name: 'Apple Watch Series 7 45mm (GPS) Viền nhôm dây cao su | Chính hãng VN/A',
          old: '12.999.000đ',
          current: '10.590.000 ₫',
          sold: '99 đã bán',
          brand: 'SmartStore',
          origin_name: 'VN/A',
          check: 'Yêu thích',
          percent: '10%',
          label: 'GIẢM',
        },
        {
          id: 18,
          url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/s/e/series_7-45-thumb_1.jpg',
          name: 'Apple Watch Series 7 45mm (GPS) Viền nhôm dây cao su | Chính hãng VN/A',
          old: '12.999.000đ',
          current: '10.590.000 ₫',
          sold: '99 đã bán',
          brand: 'SmartStore',
          origin_name: 'VN/A',
          check: 'Yêu thích',
          percent: '10%',
          label: 'GIẢM',
        },
        {
          id: 18,
          url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/s/e/series_7-45-thumb_1.jpg',
          name: 'Apple Watch Series 7 45mm (GPS) Viền nhôm dây cao su | Chính hãng VN/A',
          old: '12.999.000đ',
          current: '10.590.000 ₫',
          sold: '99 đã bán',
          brand: 'SmartStore',
          origin_name: 'VN/A',
          check: 'Yêu thích',
          percent: '10%',
          label: 'GIẢM',
        },
        {
          id: 18,
          url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/s/e/series_7-45-thumb_1.jpg',
          name: 'Apple Watch Series 7 45mm (GPS) Viền nhôm dây cao su | Chính hãng VN/A',
          old: '12.999.000đ',
          current: '10.590.000 ₫',
          sold: '99 đã bán',
          brand: 'SmartStore',
          origin_name: 'VN/A',
          check: 'Yêu thích',
          percent: '10%',
          label: 'GIẢM',
        },
        {
          id: 18,
          url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/s/e/series_7-45-thumb_1.jpg',
          name: 'Apple Watch Series 7 45mm (GPS) Viền nhôm dây cao su | Chính hãng VN/A',
          old: '12.999.000đ',
          current: '10.590.000 ₫',
          sold: '99 đã bán',
          brand: 'SmartStore',
          origin_name: 'VN/A',
          check: 'Yêu thích',
          percent: '10%',
          label: 'GIẢM',
        },
        {
          id: 18,
          url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/s/e/series_7-45-thumb_1.jpg',
          name: 'Apple Watch Series 7 45mm (GPS) Viền nhôm dây cao su | Chính hãng VN/A',
          old: '12.999.000đ',
          current: '10.590.000 ₫',
          sold: '99 đã bán',
          brand: 'SmartStore',
          origin_name: 'VN/A',
          check: 'Yêu thích',
          percent: '10%',
          label: 'GIẢM',
        },
        {
          id: 18,
          url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/s/e/series_7-45-thumb_1.jpg',
          name: 'Apple Watch Series 7 45mm (GPS) Viền nhôm dây cao su | Chính hãng VN/A',
          old: '12.999.000đ',
          current: '10.590.000 ₫',
          sold: '99 đã bán',
          brand: 'SmartStore',
          origin_name: 'VN/A',
          check: 'Yêu thích',
          percent: '10%',
          label: 'GIẢM',
        },
        {
          id: 18,
          url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/s/e/series_7-45-thumb_1.jpg',
          name: 'Apple Watch Series 7 45mm (GPS) Viền nhôm dây cao su | Chính hãng VN/A',
          old: '12.999.000đ',
          current: '10.590.000 ₫',
          sold: '99 đã bán',
          brand: 'SmartStore',
          origin_name: 'VN/A',
          check: 'Yêu thích',
          percent: '10%',
          label: 'GIẢM',
        },
        {
          id: 18,
          url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/s/e/series_7-45-thumb_1.jpg',
          name: 'Apple Watch Series 7 45mm (GPS) Viền nhôm dây cao su | Chính hãng VN/A',
          old: '12.999.000đ',
          current: '10.590.000 ₫',
          sold: '99 đã bán',
          brand: 'SmartStore',
          origin_name: 'VN/A',
          check: 'Yêu thích',
          percent: '10%',
          label: 'GIẢM',
        },
        {
          id: 18,
          url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/s/e/series_7-45-thumb_1.jpg',
          name: 'Apple Watch Series 7 45mm (GPS) Viền nhôm dây cao su | Chính hãng VN/A',
          old: '12.999.000đ',
          current: '10.590.000 ₫',
          sold: '99 đã bán',
          brand: 'SmartStore',
          origin_name: 'VN/A',
          check: 'Yêu thích',
          percent: '10%',
          label: 'GIẢM',
        },
        {
          id: 18,
          url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/s/e/series_7-45-thumb_1.jpg',
          name: 'Apple Watch Series 7 45mm (GPS) Viền nhôm dây cao su | Chính hãng VN/A',
          old: '12.999.000đ',
          current: '10.590.000 ₫',
          sold: '99 đã bán',
          brand: 'SmartStore',
          origin_name: 'VN/A',
          check: 'Yêu thích',
          percent: '10%',
          label: 'GIẢM',
        },
        {
          id: 18,
          url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/s/e/series_7-45-thumb_1.jpg',
          name: 'Apple Watch Series 7 45mm (GPS) Viền nhôm dây cao su | Chính hãng VN/A',
          old: '12.999.000đ',
          current: '10.590.000 ₫',
          sold: '99 đã bán',
          brand: 'SmartStore',
          origin_name: 'VN/A',
          check: 'Yêu thích',
          percent: '10%',
          label: 'GIẢM',
        },
        {
          id: 18,
          url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/s/e/series_7-45-thumb_1.jpg',
          name: 'Apple Watch Series 7 45mm (GPS) Viền nhôm dây cao su | Chính hãng VN/A',
          old: '12.999.000đ',
          current: '10.590.000 ₫',
          sold: '99 đã bán',
          brand: 'SmartStore',
          origin_name: 'VN/A',
          check: 'Yêu thích',
          percent: '10%',
          label: 'GIẢM',
        },
        {
          id: 18,
          url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/s/e/series_7-45-thumb_1.jpg',
          name: 'Apple Watch Series 7 45mm (GPS) Viền nhôm dây cao su | Chính hãng VN/A',
          old: '12.999.000đ',
          current: '10.590.000 ₫',
          sold: '99 đã bán',
          brand: 'SmartStore',
          origin_name: 'VN/A',
          check: 'Yêu thích',
          percent: '10%',
          label: 'GIẢM',
        },
        {
          id: 18,
          url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/s/e/series_7-45-thumb_1.jpg',
          name: 'Apple Watch Series 7 45mm (GPS) Viền nhôm dây cao su | Chính hãng VN/A',
          old: '12.999.000đ',
          current: '10.590.000 ₫',
          sold: '99 đã bán',
          brand: 'SmartStore',
          origin_name: 'VN/A',
          check: 'Yêu thích',
          percent: '10%',
          label: 'GIẢM',
        },
        {
          id: 18,
          url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/s/e/series_7-45-thumb_1.jpg',
          name: 'Apple Watch Series 7 45mm (GPS) Viền nhôm dây cao su | Chính hãng VN/A',
          old: '12.999.000đ',
          current: '10.590.000 ₫',
          sold: '99 đã bán',
          brand: 'SmartStore',
          origin_name: 'VN/A',
          check: 'Yêu thích',
          percent: '10%',
          label: 'GIẢM',
        },
        {
          id: 18,
          url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/s/e/series_7-45-thumb_1.jpg',
          name: 'Apple Watch Series 7 45mm (GPS) Viền nhôm dây cao su | Chính hãng VN/A',
          old: '12.999.000đ',
          current: '10.590.000 ₫',
          sold: '99 đã bán',
          brand: 'SmartStore',
          origin_name: 'VN/A',
          check: 'Yêu thích',
          percent: '10%',
          label: 'GIẢM',
        },
        {
          id: 18,
          url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/s/e/series_7-45-thumb_1.jpg',
          name: 'Apple Watch Series 7 45mm (GPS) Viền nhôm dây cao su | Chính hãng VN/A',
          old: '12.999.000đ',
          current: '10.590.000 ₫',
          sold: '99 đã bán',
          brand: 'SmartStore',
          origin_name: 'VN/A',
          check: 'Yêu thích',
          percent: '10%',
          label: 'GIẢM',
        },
        {
          id: 18,
          url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/s/e/series_7-45-thumb_1.jpg',
          name: 'Apple Watch Series 7 45mm (GPS) Viền nhôm dây cao su | Chính hãng VN/A',
          old: '12.999.000đ',
          current: '10.590.000 ₫',
          sold: '99 đã bán',
          brand: 'SmartStore',
          origin_name: 'VN/A',
          check: 'Yêu thích',
          percent: '10%',
          label: 'GIẢM',
        },
        {
          id: 18,
          url: 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/small_image/9df78eab33525d08d6e5fb8d27136e95/s/e/series_7-45-thumb_1.jpg',
          name: 'Apple Watch Series 7 45mm (GPS) Viền nhôm dây cao su | Chính hãng VN/A',
          old: '12.999.000đ',
          current: '10.590.000 ₫',
          sold: '99 đã bán',
          brand: 'SmartStore',
          origin_name: 'VN/A',
          check: 'Yêu thích',
          percent: '10%',
          label: 'GIẢM',
        },
      ]

  constructor() { }

  ngOnInit(): void {
  }

}
